name: Windows Test

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  CI:
    strategy:
      matrix:
        python-version: [3.6.x, 3.7.x, 3.8.x]
        python-arch: ["x86", "x64"]

    env:
      PYTHONHASHSEED: 32
      TZ: "CST-8"

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build, and test
      run: |
        cd ./web/
        npm ci
        npm run build
      env:
        CI: true

    - name: Setup Python ${{matrix.python-version}} ${{matrix.python-arch}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}
        architecture: ${{matrix.python-arch}}
        
    - name: Install dependencies
      run: |
        git lfs install
        git lfs pull
        python -m pip install --upgrade pip wheel setuptools pytest
        python -m pip install -r requirements.txt
        python -m pip install autodocsumm sphinx_rtd_theme jieba

    - name: Format log path and name
      id: log_info
      run: |
        echo "::set-output name=log_name::win_$(date -d today +%Y%m%d)_${{matrix.python-version}}_${{matrix.python-arch}}_$(echo ${GITHUB_SHA:0:7})"
        echo "::set-output name=log_archive_path::./log_archive/"

    - name: Run Test Case
      timeout-minutes: 60
      run: |
        mkdir -p ${{steps.log_info.outputs.log_archive_path}}
        python -W ignore::DeprecationWarning -m pytest --no-print-logs `
          --log-level=DEBUG `
          --log-file=${{steps.log_info.outputs.log_archive_path}}${{steps.log_info.outputs.log_name}}.log

    - name: Upload log to artifact
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: ${{steps.log_info.outputs.log_name}}
        path: ${{steps.log_info.outputs.log_archive_path}}
